name: Code style check
on:
    push:
        branches:
            - master
    pull_request: ~

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version:
                    - '8.1'

        name: PHP ${{ matrix.php_version }}
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
            - run: composer install
            - run: composer cscheck
